name: Setup
description: Checkout, setup Node, install dependencies

inputs:
  node-version:
    description: Node.js version to install
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Setup Node
      uses: actions/setup-node@v7
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm

    - name: Install dependencies
      run: npm ci
      shell: bash
